spring:
  datasource:
    url: jdbc:h2:~/h2-db/hong-ckeditor
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update    # ???? table? ????
    properties:
      hibernate:
      #show_sql: true    # ?????? ???? ???, logger? ?? ?? (system.out?? ???)
      #format_sql: true

logging.level:
  org.hibernate.SQL: debug


hong:
  img:
    path: 'D:\hongFileDir\hongCkEditorFile\'
  ckImg:
    pattern: '/ckImage/**'
    path: 'D:/hongFileDir/hongCkEditorFile/ckImage/'